title: keine.company
email: mail@keine.company
description: >-
  work in progress
baseurl: ""
url: "https://keine.company"
github_username:  keinecompany
twitter_username: keinecompany

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude: 
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
